apiVersion: v1
kind: Service
metadata:
  name: datanode1
spec:
  selector:
    app: datanode1
  ports:
  - name: dn-web
    port: 50075
    targetPort: 50075
  - name: dn-data
    port: 9864
    targetPort: 9864
  type: ClusterIP
