apiVersion: apps/v1
kind: Deployment
metadata:
  name: datanode1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datanode1
  template:
    metadata:
      labels:
        app: datanode1
    spec:
      containers:
      - name: datanode1
        image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
        ports:
        - containerPort: 50075
        - containerPort: 9864
        env:
        - name: CORE_CONF_fs_defaultFS
          value: hdfs://namenode1:8020
        - name: HDFS_CONF_dfs_webhdfs_enabled
          value: "true"
