apiVersion: v1
kind: Service
metadata:
  name: nifi
spec:
  selector:
    app: nifi
  ports:
  - name: webui
    port: 8443
    targetPort: 8443
  - name: custom
    port: 5050
    targetPort: 5050
  type: ClusterIP
