apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-submit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-submit
  template:
    metadata:
      labels:
        app: spark-submit
    spec:
      containers:
        - name: spark-submit
          image: bitnami/spark:3.5.3
          env:
            - name: SPARK_MODE
              value: client
            - name: SPARK_MASTER_URL
              value: spark://spark-master:7077
            - name: HOME
              value: /tmp  
          command:
            - /bin/bash
            - "-c"
            - |
              /opt/bitnami/spark/bin/spark-submit \
              --master $SPARK_MASTER_URL \
              --class org.apache.spark.examples.SparkPi \
              /opt/bitnami/spark/examples/jars/spark-examples_2.12.jar 100
