apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
        - name: spark-master
          image: bitnami/spark:3.5.3
          ports:
            - containerPort: 7077
            - containerPort: 8080
          env:
            - name: SPARK_MODE
              value: "master"
            - name: SPARK_RPC_AUTHENTICATION_ENABLED
              value: "no"
          command:
            - /bin/bash
            - -c
            - |
              /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.master.Master \
              --host $(hostname) \
              --port 7077 \
              --webui-port 8080
