apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker-2
  template:
    metadata:
      labels:
        app: spark-worker-2
    spec:
      containers:
      - name: spark-worker-2
        image: bitnami/spark:3.5.3
        env:
        - name: SPARK_MODE
          value: worker
        - name: SPARK_MASTER_URL
          value: spark://spark-master:7077
        ports:
        - containerPort: 8081
