apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-init
spec:
  template:
    spec:
      containers:
      - name: kafka-init
        image: bitnami/kafka:3.9.0
        command:
          - /bin/bash
          - -c
          - |
            # Espera a que Kafka esté listo
            until kafka-topics.sh --bootstrap-server kafka:9092 --list > /dev/null 2>&1; do
              echo "Esperando a que Kafka esté listo..."
              sleep 2
            done

            # Crea topics si no existen
            kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic flight-delay-ml-request --partitions 1 --replication-factor 1
            kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic flight-delay-ml-response --partitions 1 --replication-factor 1
      restartPolicy: OnFailure
