apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-import-job
spec:
  template:
    spec:
      containers:
      - name: mongo-import
        image: mongo:4.0
        command: ["/bin/bash", "-c"]
        args:
          - /docker-entrypoint-initdb.d/import_distances.sh
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: init-scripts
        - mountPath: /data
          name: import-data
      restartPolicy: Never
      volumes:
      - name: init-scripts
        hostPath:
          path: /mnt/IBDN_Practica_Final/resources
          type: Directory
      - name: import-data
        hostPath:
          path: /mnt/IBDN_Practica_Final/data
          type: Directory
