apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
      - name: nifi
        image: apache/nifi:1.25.0
        ports:
        - containerPort: 8443
        - containerPort: 5050
        env:
        - name: SINGLE_USER_CREDENTIALS_USERNAME
          value: "admin"
        - name: SINGLE_USER_CREDENTIALS_PASSWORD
          value: "098765432100"
        - name: NIFI_WEB_HTTP_PORT
          value: "8443"
        volumeMounts:
        - name: nifi-config
          mountPath: /opt/nifi/nifi-current/conf
        - name: nifi-output
          mountPath: /opt/nifi/output
      volumes:
      - name: nifi-config
        persistentVolumeClaim:
          claimName: nifi-config-pvc
      - name: nifi-output
        hostPath:
          path: /mnt/IBDN_Practica_Final/nifi_output   # Cambia a la ruta absoluta donde tienes la carpeta nifi_output
          type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nifi-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nifi-service
spec:
  type: NodePort
  selector:
    app: nifi
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
      nodePort: 30443
    - name: additional-port
      protocol: TCP
      port: 5050
      targetPort: 5050
      # nodePort: 30505  # opcional si quieres exponer este puerto también fuera del cluster
