apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker-1
  template:
    metadata:
      labels:
        app: spark-worker-1
    spec:
      containers:
      - name: spark-worker
        image: jorgemdiez/my-spark-job:latest   # Imagen personalizada con JAR y modelos
        env:
        - name: SPARK_MODE
          value: "worker"
        - name: SPARK_MASTER_URL
          value: "spark://spark-master-service:7077"
        ports:
        - containerPort: 8081
        # No mounts ni volúmenes necesarios

---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker-1-service
spec:
  selector:
    app: spark-worker-1
  type: NodePort
  ports:
  - name: spark-worker-ui
    protocol: TCP
    port: 8084
    targetPort: 8081
    nodePort: 30013
