apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker-2
  template:
    metadata:
      labels:
        app: spark-worker-2
    spec:
      containers:
      - name: spark-worker
        image: jorgemdiez/my-spark-job:latest  # Cambiado a la imagen personalizada
        env:
        - name: SPARK_MODE
          value: "worker"
        - name: SPARK_MASTER_URL
          value: "spark://spark-master-service:7077"
        ports:
        - containerPort: 8081
        # Ya no necesita mounts porque todo está en la imagen
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker-2-service
spec:
  selector:
    app: spark-worker-2
  type: NodePort
  ports:
  - name: spark-worker-ui
    protocol: TCP
    port: 8085
    targetPort: 8081
    nodePort: 30012