apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: jorgemdiez/my-spark-job:latest  # Imagen personalizada con todo dentro
        env:
        - name: SPARK_MODE
          value: "master"
        - name: SPARK_RPC_AUTHENTICATION_ENABLED
          value: "no"
        ports:
        - containerPort: 7077
        - containerPort: 8080
        # No volumeMounts ni volumes necesarios

---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-service
spec:
  selector:
    app: spark-master
  type: NodePort
  ports:
  - name: spark-master-port
    protocol: TCP
    port: 7077
    targetPort: 7077
    nodePort: 30010
  - name: spark-master-ui
    protocol: TCP
    port: 8086
    targetPort: 8080
    nodePort: 30011
