apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker-1
  template:
    metadata:
      labels:
        app: spark-worker-1
    spec:
      containers:
      - name: spark-worker
        image: bitnami/spark:3.5.3
        env:
        - name: SPARK_MODE
          value: "worker"
        - name: SPARK_MASTER_URL
          value: "spark://spark-master:7077"
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: scala-target
          mountPath: /home/ibdn/practica_creativa/flight_prediction/target/scala-2.12
        - name: models
          mountPath: /home/ibdn/practica_creativa/models
      volumes:
      - name: scala-target
        hostPath:
          path: /mnt/volumen/IBDN_Practica_Final/flight_prediction/target/scala-2.12  # Cambia por ruta absoluta
          type: Directory
      - name: models
        hostPath:
          path: /mnt/volumen/IBDN_Practica_Final/models                              # Cambia por ruta absoluta
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker-1-service
spec:
  selector:
    app: spark-worker-1
  type: NodePort
  ports:
  - name: spark-worker-ui
    protocol: TCP
    port: 8084
    targetPort: 8081
    nodePort: 30013
