apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: daveelpatoupm/proxy:latest  # <-- igual aquí: sube esta imagen al registry
        ports:
        - containerPort: 3000
